### ISSUE TITLE
Add bold, italics, bold-itlatics, and monospaced font

### ISSUE THREAD

**Issue by ianpan870102** [IagoLast/paper#1]
The CMU font package actually comes with all these fonts. We'd love to have them included so Typora doesn't use its default bold/italics rendering.

**Comment by ianpan870102** [comment]
```css
@font-face {
	font-family: "Computer Modern";
  font-style: normal;
	font-weight: normal;
	src: url('./paper/cmunrm.ttf');
}

@font-face {
	font-family: "Computer Modern";
  font-style: italic;
  font-weight: normal;
	src: url('./paper/cmunti.ttf');
}

@font-face {
	font-family: "Computer Modern";
  font-style: normal;
	font-weight: bold;
	src: url('./paper/cmunbx.ttf');
}

@font-face {
	font-family: "Computer Modern";
  font-style: italic;
  font-weight: bold;
	src: url('./paper/cmunbi.ttf');
}
```
